"""remove redundant primary key indexes

Revision ID: efa0f0630c23
Revises: 736b01bf65db
Create Date: 2026-07-19 19:40:34.210833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa0f0630c23'
down_revision: Union[str, Sequence[str], None] = '736b01bf65db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_antenna_id'), table_name='antenna')
    op.drop_index(op.f('ix_intervention_id'), table_name='intervention')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_intervention_id'), 'intervention', ['id'], unique=False)
    op.create_index(op.f('ix_antenna_id'), 'antenna', ['id'], unique=False)
    # ### end Alembic commands ###
